<template>
  <MenuNoneSearch class="sneakers-menu" />
  <SneakersContent class="sneakers-content" :productsID="products" />
  <AppFooter />
</template>
<script>
import MenuNoneSearch from "@/layouts/MenuNoneSearch.vue";
import SneakersContent from "@/layouts/SneakersContent.vue";
import AppFooter from "@/layouts/AppFooter.vue";

export default {
  components: { MenuNoneSearch, SneakersContent, AppFooter },
  data() {
    return {
      products: [
        {
          id: 1,
          name: "vans",
          price: 40000,
          image1: require("../../images/product/1_pair/1.jpg"),
          image2: require("../../images/product/1_pair/2.jpg"),
          image3: require("../../images/product/1_pair/3.jpg"),
          image4: require("../../images/product/1_pair/4.jpg"),
          image5: require("../../images/product/1_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 2,
          name: "vans",
          price: 45000,
          image1: require("../../images/product/2_pair/1.jpg"),
          image2: require("../../images/product/2_pair/2.jpg"),
          image3: require("../../images/product/2_pair/3.jpg"),
          image4: require("../../images/product/2_pair/4.jpg"),
          image5: require("../../images/product/2_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 3,
          name: "vans",
          price: 42000,
          image1: require("../../images/product/3_pair/1.jpg"),
          image2: require("../../images/product/3_pair/2.jpg"),
          image3: require("../../images/product/3_pair/3.jpg"),
          image4: require("../../images/product/3_pair/4.jpg"),
          image5: require("../../images/product/3_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 4,
          name: "vans",
          price: 39000,
          image1: require("../../images/product/4_pair/1.jpg"),
          image2: require("../../images/product/4_pair/2.jpg"),
          image3: require("../../images/product/4_pair/3.jpg"),
          image4: require("../../images/product/4_pair/4.jpg"),
          image5: require("../../images/product/4_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 5,
          name: "adidas",
          price: 40000,
          image1: require("../../images/product/5_pair/1.jpg"),
          image2: require("../../images/product/5_pair/2.jpg"),
          image3: require("../../images/product/5_pair/3.jpg"),
          image4: require("../../images/product/5_pair/4.jpg"),
          image5: require("../../images/product/5_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 6,
          name: "puma",
          price: 40000,
          image1: require("../../images/product/6_pair/1.jpg"),
          image2: require("../../images/product/6_pair/2.jpg"),
          image3: require("../../images/product/6_pair/3.jpg"),
          image4: require("../../images/product/6_pair/4.jpg"),
          // image5: require("../../images/product/6_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 7,
          name: "reebok",
          price: 40000,
          image1: require("../../images/product/7_pair/1.jpg"),
          image2: require("../../images/product/7_pair/2.jpg"),
          image3: require("../../images/product/7_pair/3.jpg"),
          image4: require("../../images/product/7_pair/4.jpg"),
          image5: require("../../images/product/7_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 8,
          name: "adidas",
          price: 40000,
          image1: require("../../images/product/8_pair/1.jpg"),
          image2: require("../../images/product/8_pair/2.jpg"),
          image3: require("../../images/product/8_pair/3.jpg"),
          image4: require("../../images/product/8_pair/4.jpg"),
          // image5: require("../../images/product/8_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 9,
          name: "puma",
          price: 40000,
          image1: require("../../images/product/9_pair/1.jpg"),
          image2: require("../../images/product/9_pair/2.jpg"),
          image3: require("../../images/product/9_pair/3.jpg"),
          image4: require("../../images/product/9_pair/4.jpg"),
          image5: require("../../images/product/9_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 10,
          name: "new balance",
          price: 40000,
          image1: require("../../images/product/10_pair/1.jpg"),
          image2: require("../../images/product/10_pair/2.jpg"),
          image3: require("../../images/product/10_pair/3.jpg"),
          image4: require("../../images/product/10_pair/4.jpg"),
          // image5: require("../../images/product/10_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 11,
          name: "adidas",
          price: 13000,
          image1: require("../../images/product/11_pair/1.jpg"),
          image2: require("../../images/product/11_pair/2.jpg"),
          image3: require("../../images/product/11_pair/3.jpg"),
          image4: require("../../images/product/11_pair/4.jpg"),
          image5: require("../../images/product/11_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 12,
          name: "breggs",
          price: 40000,
          image1: require("../../images/product/12_pair/1.jpg"),
          image2: require("../../images/product/12_pair/2.jpg"),
          image3: require("../../images/product/12_pair/3.jpg"),
          image4: require("../../images/product/12_pair/4.jpg"),
          // image5: require("../../images/product/12_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 13,
          name: "new balance",
          price: 39000,
          image1: require("../../images/product/13_pair/1.jpg"),
          image2: require("../../images/product/13_pair/2.jpg"),
          image3: require("../../images/product/13_pair/3.jpg"),
          image4: require("../../images/product/13_pair/4.jpg"),
          image5: require("../../images/product/13_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 14,
          name: "reebok",
          price: 27000,
          image1: require("../../images/product/14_pair/1.jpg"),
          image2: require("../../images/product/14_pair/2.jpg"),
          image3: require("../../images/product/14_pair/3.jpg"),
          image4: require("../../images/product/14_pair/4.jpg"),
          image5: require("../../images/product/14_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 15,
          name: "reebok",
          price: 19000,
          image1: require("../../images/product/15_pair/1.jpg"),
          image2: require("../../images/product/15_pair/2.jpg"),
          image3: require("../../images/product/15_pair/3.jpg"),
          image4: require("../../images/product/15_pair/4.jpg"),
          image5: require("../../images/product/15_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 16,
          name: "new balance",
          price: 15000,
          image1: require("../../images/product/16_pair/1.jpg"),
          image2: require("../../images/product/16_pair/2.jpg"),
          image3: require("../../images/product/16_pair/3.jpg"),
          image4: require("../../images/product/16_pair/4.jpg"),
          image5: require("../../images/product/16_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 17,
          name: "vans",
          price: 40000,
          image1: require("../../images/product/17_pair/1.jpg"),
          image2: require("../../images/product/17_pair/2.jpg"),
          image3: require("../../images/product/17_pair/3.jpg"),
          image4: require("../../images/product/17_pair/4.jpg"),
          image5: require("../../images/product/17_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 18,
          name: "new balance",
          price: 23000,
          image1: require("../../images/product/18_pair/1.jpg"),
          image2: require("../../images/product/18_pair/2.jpg"),
          image3: require("../../images/product/18_pair/3.jpg"),
          image4: require("../../images/product/18_pair/4.jpg"),
          image5: require("../../images/product/18_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 19,
          name: "new balance",
          price: 41000,
          image1: require("../../images/product/19_pair/1.jpg"),
          image2: require("../../images/product/19_pair/2.jpg"),
          image3: require("../../images/product/19_pair/3.jpg"),
          image4: require("../../images/product/19_pair/4.jpg"),
          image5: require("../../images/product/19_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 20,
          name: "adidas",
          price: 10000,
          image1: require("../../images/product/20_pair/1.jpg"),
          image2: require("../../images/product/20_pair/2.jpg"),
          image3: require("../../images/product/20_pair/3.jpg"),
          // image4: require("../../images/product/20_pair/4.jpg"),
          // image5: require("../../images/product/20_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 21,
          name: "reebok",
          price: 45000,
          image1: require("../../images/product/21_pair/1.jpg"),
          image2: require("../../images/product/21_pair/2.jpg"),
          image3: require("../../images/product/21_pair/3.jpg"),
          image4: require("../../images/product/21_pair/4.jpg"),
          image5: require("../../images/product/21_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 22,
          name: "vans",
          price: 24000,
          image1: require("../../images/product/22_pair/1.jpg"),
          image2: require("../../images/product/22_pair/2.jpg"),
          image3: require("../../images/product/22_pair/3.jpg"),
          image4: require("../../images/product/22_pair/4.jpg"),
          image5: require("../../images/product/22_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 23,
          name: "reebok",
          price: 38000,
          image1: require("../../images/product/23_pair/1.jpg"),
          image2: require("../../images/product/23_pair/2.jpg"),
          image3: require("../../images/product/23_pair/3.jpg"),
          image4: require("../../images/product/23_pair/4.jpg"),
          image5: require("../../images/product/23_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 24,
          name: "adidas",
          price: 17000,
          image1: require("../../images/product/24_pair/1.jpg"),
          image2: require("../../images/product/24_pair/2.jpg"),
          image3: require("../../images/product/24_pair/3.jpg"),
          image4: require("../../images/product/24_pair/4.jpg"),
          image5: require("../../images/product/24_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 25,
          name: "reebok",
          price: 33000,
          image1: require("../../images/product/25_pair/1.jpg"),
          image2: require("../../images/product/25_pair/2.jpg"),
          image3: require("../../images/product/25_pair/3.jpg"),
          image4: require("../../images/product/25_pair/4.jpg"),
          image5: require("../../images/product/25_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 26,
          name: "new balance",
          price: 47000,
          image1: require("../../images/product/26_pair/1.jpg"),
          image2: require("../../images/product/26_pair/2.jpg"),
          image3: require("../../images/product/26_pair/3.jpg"),
          image4: require("../../images/product/26_pair/4.jpg"),
          image5: require("../../images/product/26_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 27,
          name: "puma",
          price: 32000,
          image1: require("../../images/product/27_pair/1.jpg"),
          image2: require("../../images/product/27_pair/2.jpg"),
          image3: require("../../images/product/27_pair/3.jpg"),
          image4: require("../../images/product/27_pair/4.jpg"),
          image5: require("../../images/product/27_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
        {
          id: 28,
          name: "vans",
          price: 40000,
          image1: require("../../images/product/28_pair/1.jpg"),
          image2: require("../../images/product/28_pair/2.jpg"),
          image3: require("../../images/product/28_pair/3.jpg"),
          image4: require("../../images/product/28_pair/4.jpg"),
          image5: require("../../images/product/28_pair/5.jpg"),
          favorite: false,
          discount: true,
          trend: false,
        },
      ],
    };
  },
};
</script>
<style lang="css">
.sneakers-menu {
  margin-bottom: 20px;
}
.sneakers-content {
  min-height: 80vh;
}
</style>
